### ISSUE TITLE
doesn't work as of today, gives fatal error on game startup

### ISSUE THREAD

**Issue by Legushka26** [Dimava/dimava.github.io#6]
Hello. Thank you for this useful tool! It was always working perfectly fine but it stopped working today. If installing it by adding the https files, the game shows this error message on startup:

"Oh oh, it looks like you ran into a fatal error

This is the error code:

ReferenceError: game is not defined at a0_0x193066
(file:///C:/Games/Steam/steamapps/common/Increlution/resources/app/gniller-min.js:1:873008) at eval (eval at updatehack
(https://dimava.github.io/mods/inc/speedhack.js:81:2), <anonymous>:1:28)"

If installing it locally then the game works as usual but the speedhack and other features just don't work or show up at all. A couple of days ago everything was working fine.

**Comment by Dimava** [comment]
Reproduction needed
